MiniShopApp/MiniShopApp.WebUI/Controllers/CardController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MiniShopApp.Business.Abstract;
using MiniShopApp.WebUI.Identity;
using MiniShopApp.WebUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MiniShopApp.WebUI.Controllers
{
    public class CardController : Controller
    {
        private ICardService _cardService;
        private UserManager<User> _userManager;

        public CardController(ICardService cardService, UserManager<User> userManager)
        {
            _cardService = cardService;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var userId = _userManager.GetUserId(User);
            var card = _cardService.GetCardByUserId(userId);
            var model = new CardModel()
            {
                CardId = card.Id,
                CardItems = card.CardItems.Select(i => new CardItemModel()
                {
                    CardItemId = i.Id,
                    ProductId = i.ProductId,
                    Name = i.Product.Name,
                    Price = (double)i.Product.Price,
                    ImageUrl = i.Product.ImageUrl,
                    Quantity = i.Quantity
                }).ToList()
            };
            return View(model);
        }
    }
}

MiniShopApp/MiniShopApp.WebUI/Views/Card/Index.cshtml
@model CardModel
<h6 class="display-4">Shopping Card</h6>
<hr />
@if (Model.CardItems.Count == 0)
{
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-warning">
                Sepetinizde ürün yoktur!
            </div>
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-8">
            <div>
                <h6>Card Items</h6>
                <table class="table table-sm table-hover">
                    <thead>
                        <tr>
                            <th>Image</th>
                            <th>Product Name</th>
                            <th>Price</th>
                            <th>Quantity</th>
                            <th>Total</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var cardItem in Model.CardItems)
                        {
                            <tr>
                                <td>
                                    <img src="~/img/@cardItem.ImageUrl" width="50" />
                                </td>
                                <td>@cardItem.Name</td>
                                <td>@cardItem.Price</td>
                                <td>@cardItem.Quantity</td>
                                <td>@(cardItem.Price*cardItem.Quantity)</td>
                                <td>
                                    <form asp-controller="Card" asp-action="DeleteFromCard" method="post">
                                        <input type="hidden" name="productId"  value="@cardItem.ProductId" />
                                        <button type="submit" class="btn btn-sm btn-danger"><i class="fa-solid fa-circle-xmark"></i></button>
                                    </form>
                                </td>
                            </tr>
                        }

                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-4"></div>
    </div>
}